### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by liyuncc**

### CODE REVIEW

**Comment by sicheng-zhu** [comment]
Merge the initial file

**Comment by liyuncc** [comment]
Hi Philip,

Did you make any changes to p1.php? I didn't see it. I saw you merged the
initial file.
After you update it, please send me the link to your pull request, thanks!

Liyun

**Comment by sicheng-zhu** [comment]
Hi Liyun,

I have create a pull request.

Thanks,
Sicheng

**Comment by liyuncc** [comment]
Got it!
Here's my pull request:
https://github.com/liyuncc/GroupProject2/pull/3

**Pull request merged**
